apiVersion: v1
kind: PersistentVolume
metadata:
  name: myfirstpv
  labels:
    name: myfirstpv
spec:
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: "/mnt/data"
