apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myfirstpvc
spec:
  selector:
    matchLabels:
      name: myfirstpv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
